[package]
description = "Rust local DNS adblocker"
documentation = "README.md"
edition = "2021"
license = "MIT"
name = "rhole"
version = "0.1.1"

[[bin]]
name = "rhole"

[profile.release]
codegen-units = 1
debug-assertions = false
lto = "thin"
opt-level = 'z'
strip = "debuginfo"

[dependencies]
anyhow = { version = "1.0.66", default-features = false, features = ["std"] }
bytes = { version = "1.2.1", default_features = false }
clap = { version = "4.0.18", default-features = false, features = [
    "color",
    "derive",
    "std",
    "suggestions",
] }
dns-message-parser = { version = "0.7.0", default-features = false }
env_logger = { version = "0.9.1", default-features = false, features = [
    "atty",
    "humantime",
    "termcolor",
] }
log = { version = "0.4.17", default-features = false }
regex = { version = "1.6.0", default-features = false, features = [
    "perf",
    "std",
    "unicode",
] }
reqwest = { version = "0.11.12", default-features = false, features = ["json"] }
serde = { version = "1.0.147", default-features = false, features = [
    "derive",
    "std",
] }
serde_yaml = { version = "0.9.14", default-features = false }
tokio = { version = "1.21.2", default-features = false, features = [
    "fs",
    "macros",
    "net",
    "rt-multi-thread",
] }
