[package]
name = "rhole"
version = "0.1.0"
edition = "2021"

[profile.release]
strip = "debuginfo"
debug-assertions = false
lto = "thin"

[dependencies]
anyhow = { version = "= 1.0.65", default-features = false, features = ["std"] }
clap = { version = "= 3.2.17", default-features = false, features = [
    "color",
    "derive",
    "std",
    "suggestions",
] }
dns-parser = { version = "= 0.8.0", default-features = false }
env_logger = { version = "= 0.9.0", default-features = false, features = [
    "atty",
    "termcolor",
    "humantime",
] }
log = { version = "= 0.4.17", default-features = false }
regex = { version = "= 1.6.0", default-features = false, features = [
    "perf",
    "std",
    "unicode"
] }
reqwest = { version = "= 0.11.11", default-features = false, features = [
    "native-tls-vendored",
    "json",
] }
serde = { version = "= 1.0.144", default-features = false, features = [
    "derive",
    "std",
] }
serde_yaml = { version = "= 0.9.10", default-features = false }
tokio = { version = "= 1.20.1", default-features = false, features = [
    "fs",
    "macros",
    "net",
    "rt-multi-thread",
] }
