[package]
name = "dns-filter"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "*", features = ["derive"]}
anyhow = "*"
serde = { version = "*", features = ["derive"] }
serde_yaml = "*"
dns-parser = "*"
tokio = { version = "*", features = ["full"] }
