[package]
authors = ["LIAUD Corentin <corentin.liaud@orange.fr>"]
description = "Rust local DNS adblocker"
edition = "2021"
license = "MIT"
name = "rhole"
readme = "README.md"
repository = "https://github.com/cocool97/rhole"
version = "0.1.2"

[[bin]]
name = "rhole"

[profile.release]
codegen-units = 1
debug-assertions = false
lto = "thin"
opt-level = 'z'
strip = "debuginfo"

[dependencies]
anyhow = { version = "= 1.0.66" }
async-trait = { version = "= 0.1.59" }
bytes = { version = "= 1.3.0" }
clap = { version = "= 4.0.29", features = ["derive"] }
env_logger = { version = "= 0.10.0" }
log = { version = "= 0.4.17" }
regex = { version = "= 1.7.0" }
reqwest = { version = "= 0.11.13" }
serde = { version = "= 1.0.148", features = ["derive"] }
serde_yaml = { version = "= 0.9.14" }
sled = { version = "= 0.34.7" }
tokio = { version = "= 1.22.0", features = ["fs", "macros", "rt-multi-thread"] }
trust-dns-client = { version = "= 0.22.0" }
trust-dns-resolver = { version = "= 0.22.0", features = ["tokio-runtime"] }
trust-dns-server = { version = "= 0.22.0", features = ["tokio-rustls"] }

[package.metadata.generate-rpm]
assets = [
    { source = "config.yml", dest = "/etc/rhole/config.yml", mode = "755", config = true },
    { source = "rhole.service", dest = "/etc/systemd/system/rhole.service", mode = "755" },
    { source = "target/armv7-unknown-linux-musleabihf/release/rhole", dest = "/usr/bin/rhole", mode = "755" },
]

[package.metadata.deb]
assets = [
    [
        "/etc/rhole/config.yml",
        "755",
        "config.yml",
    ],
    [
        "/etc/systemd/system/rhole.service",
        "755",
        "rhole.service",
    ],
    [
        "/usr/bin/rhole",
        "755",
        "target/armv7-unknown-linux-musleabihf/release/rhole",
    ],
]
