[package]
authors = ["LIAUD Corentin <corentin.liaud@orange.fr>"]
description = "Rust local DNS adblocker"
edition = "2021"
license = "MIT"
name = "rhole"
readme = "README.md"
repository = "https://github.com/cocool97/rhole"
version = "0.1.0"

[[bin]]
name = "rhole"

[profile.release]
codegen-units = 1
debug-assertions = false
lto = "thin"
opt-level = 'z'
strip = "debuginfo"

[dependencies]
anyhow = { version = "= 1.0.66", default-features = false, features = ["std"] }
bytes = { version = "= 1.2.1", default_features = false }
clap = { version = "= 4.0.22", default-features = false, features = [
    "color",
    "derive",
    "std",
    "suggestions",
] }
dns-message-parser = { version = "= 0.7.0", default-features = false }
env_logger = { version = "= 0.9.3", default-features = false, features = [
    "atty",
    "humantime",
    "termcolor",
] }
log = { version = "= 0.4.17", default-features = false }
regex = { version = "= 1.7.0", default-features = false, features = [
    "perf",
    "std",
    "unicode",
] }
reqwest = { version = "= 0.11.12", default-features = false, features = ["json"] }
serde = { version = "= 1.0.147", default-features = false, features = [
    "derive",
    "std",
] }
serde_yaml = { version = "= 0.9.14", default-features = false }
sled = { version = "= 0.34.7", default-features = false, features = [
    "no_metrics",
] }
tokio = { version = "= 1.21.2", default-features = false, features = [
    "fs",
    "macros",
    "net",
    "rt-multi-thread",
] }

[package.metadata.generate-rpm]
assets = [
    { source = "config.yml", dest = "/etc/rhole/config.yml", mode = "755", config = true },
    { source = "rhole.service", dest = "/etc/systemd/system/rhole.service", mode = "755" },
    { source = "target/armv7-unknown-linux-musleabihf/release/rhole", dest = "/usr/bin/rhole", mode = "755" },
]

[package.metadata.deb]
assets = [
    [
        "/etc/rhole/config.yml",
        "755",
        "config.yml",
    ],
    [
        "/etc/systemd/system/rhole.service",
        "755",
        "rhole.service",
    ],
    [
        "/usr/bin/rhole",
        "755",
        "target/armv7-unknown-linux-musleabihf/release/rhole",
    ],
]
