# tls:
#   certificate_path: keys/crt.pem
#   pkey_path: keys/key.pem
local_hosts:
  test.lan.: "192.168.0.10"
proxy_server:
  ip: "1.1.1.1"
  port: 853
  tls_dns_name: cloudflare-dns.com
sources:
  update_interval: 5
  entries:
    - source_type: !File
      location: hosts.txt
      comment: Global hosts file
    # - source_type: !Network
    #   location: http://sbc.io/hosts/alternates/fakenews-gambling-porn/hosts
    #   comment: Remote hosts file