database_path: /etc/rhole/data/rhole.db
tls:
  certificate_path: /etc/rhole/ssl/crt.pem
  pkey_path: /etc/rhole/ssl/key.pem
html_dir: "index.html"
proxy_server:
  ip: "1.1.1.1"
  port: 853
  tls_dns_name: cloudflare-dns.com
sources:
  update_interval: 5
  entries:
    # - source_type: !File
    #   location: hosts.txt
    #   comment: Global hosts file
    - source_type: !Network
      location: http://sbc.io/hosts/alternates/fakenews-gambling-porn/hosts
      comment: Remote hosts file
net:
  dns:
    listen_addr: "0.0.0.0"
    listen_port: 53
  dot:
    listen_addr: "0.0.0.0"
    listen_port: 853
    timeout: 2
  web_interface:
    listen_addr: "0.0.0.0"
    listen_port: 443