database_path: rhole.db
tls:
  certificate_path: keys/crt.pem
  pkey_path: keys/key.pem
web_resources:
  static_files: "dist"
  index_file: "index.html"
  mount_path: "/"
proxy_server:
  ip: "1.1.1.1"
  port: 853
  tls_dns_name: cloudflare-dns.com
sources:
  update_interval: 5
  entries:
    - source_type: !File
      location: hosts.txt
      comment: Global hosts file
    # - source_type: !Network
    # location: http://sbc.io/hosts/alternates/fakenews-gambling-porn/hosts
    # comment: Remote hosts file
net:
  dns:
    listen_addr: "0.0.0.0"
    listen_port: 5053
  dot:
    listen_addr: "0.0.0.0"
    listen_port: 8053
    timeout: 2
  web_interface:
    listen_addr: "0.0.0.0"
    listen_port: 40443
