[package]
authors.workspace = true
edition.workspace = true
license.workspace = true
name = "common"
repository.workspace = true
version.workspace = true

[dependencies]
anyhow = { version = "= 1.0.71" }
serde = { version = "= 1.0.163", features = ["derive"] }
