//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "blocked_domains")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub domain_address: String,
    #[sea_orm(column_type = "Double")]
    pub insert_timestamp: f64,
    pub blocked_count: i32,
    pub whitelisted: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::blocked_requests::Entity")]
    BlockedRequests,
}

impl Related<super::blocked_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlockedRequests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
