//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel)]
#[sea_orm(table_name = "client")]
pub struct Model {
    #[sea_orm(primary_key)]
    pub id: i32,
    pub address: String,
    pub alias: Option<String>,
    #[sea_orm(column_type = "Double")]
    pub last_seen: f64,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::blocked_requests::Entity")]
    BlockedRequests,
}

impl Related<super::blocked_requests::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::BlockedRequests.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
