//! `SeaORM` Entity. Generated by sea-orm-codegen 0.12.10

pub use super::blocked_domains::Entity as BlockedDomains;
pub use super::blocked_requests::Entity as BlockedRequests;
pub use super::client::Entity as Client;
