name: Rust - Build

on: [push]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-release:
    name: "Build release binary"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Build
      run: cargo build --release